### ISSUE TITLE
Rewrite in ES6

### ISSUE THREAD

**Issue by IonicaBizau** [izuzak/benchtable#6]
Since Node >=4.0.0 supports ES6 classes, would be nice to rewrite the code using ES6 classes.
@izuzak If you agree, I can take care of that. :grin:

**Comment by izuzak** [comment]
Ha, I think that would be neat, yeah. I'd accept a pull request for that if you want to work on it :) Thanks!

**Comment by IonicaBizau** [comment]
@izuzak Great! :smile: 

I'm thinking we could use JSDoc comments and [`blah`](https://github.com/IonicaBizau/blah) to generate the README file (including the [api documentation](https://github.com/izuzak/benchtable#api-and-usage)). What do you think? :thought_balloon:

**Comment by izuzak** [comment]
> I'm thinking we could use JSDoc comments and blah to generate the README file (including the api documentation). What do you think?

I think I'm impressed by how many modules you've written. :grin: Sounds good to me :+1:

**Comment by IonicaBizau** [comment]
@izuzak Oh, thanks! :joy: I needed a way to automatize the way of building docs. [This](https://github.com/IonicaBizau/dotfiles/blob/master/blah-templates/README.ejs) is how my README template looks like (across projects). :book:
